export const BOOKING_FLOW_STYLE = {
  textPrimary: "#2f3c8c",
  textSecondary: "rgba(47, 60, 140, 0.72)",
  accent: "#4a74da",
  accentSoft: "rgba(74, 116, 218, 0.12)",
  surface: "#ffffff",
  border: "rgba(74, 116, 218, 0.16)",
  subtleSurface: "rgba(147, 206, 246, 0.08)",
  radius: "20px",
  shadow: "0px 24px 60px rgba(47, 60, 140, 0.1)",
};

export const BOOKING_FLOW_TEXT = {
  steps: ["Chọn lịch & giờ", "Thông tin liên hệ"],
  actions: {
    continue: "Tiếp tục",
    back: "Quay lại",
    close: "Đóng",
    pay: "Thanh toán",
    apply: "Áp dụng",
    reload: "Tải lại",
    upload: "Tải tệp lên",
  },
  form: {
    package: "Gói dịch vụ",
    duration: "Thời lượng",
    name: "Họ và tên",
    email: "Email",
    phone: "Số điện thoại",
    note: "Ghi chú cho KOL",
    attachments: "Tệp đính kèm (không bắt buộc)",
    scheduleTitle: "Chọn khung giờ khả dụng",
    summaryTitle: "Tổng quan đặt lịch",
    paymentTitle: "Chi tiết thanh toán",
    terms: "Điều khoản dịch vụ",
    coupon: "Mã giảm giá",
  },
  messages: {
    selectPackage: "Vui lòng chọn gói dịch vụ và thời lượng.",
    selectSchedule: "Vui lòng chọn ngày và khung giờ.",
    infoInvalid: "Vui lòng điền đầy đủ thông tin và đồng ý với điều khoản.",
    slotTaken:
      "Khung giờ này vừa được người khác đặt. Vui lòng chọn khung giờ khác.",
    dayFull: "Ngày này đã kín lịch. Vui lòng chọn thời điểm khác.",
    attachmentHint:
      "Có thể đính kèm tối đa {limit} tệp (mỗi tệp tối đa {size}MB).",
    attachmentSize: "Mỗi tệp không được vượt quá {size}MB.",
    attachmentLimit: "Bạn chỉ có thể đính kèm tối đa {limit} tệp.",
    attachmentDuplicate: "Tệp này đã được đính kèm trước đó.",
    scheduleTimeMissing:
      "Không thể xác định khung giờ đã chọn. Vui lòng tải lại và thử lại.",
    paymentFailed: "Không thể tạo đặt lịch. Vui lòng thử lại sau.",
  },
  summary: {
    kol: "KOL",
    package: "Gói dịch vụ",
    duration: "Thời lượng",
    schedule: "Lịch hẹn",
    subtotal: "Tạm tính",
    discount: "Giảm giá",
    extraFee: "Phụ phí",
    total: "Tổng thanh toán",
  },
  receipt: {
    title: "Đặt lịch thành công",
    description:
      "Vui lòng hoàn tất thanh toán trong thời gian đếm ngược để giữ chỗ.",
    invoice: "Chi tiết thanh toán",
    bookingCode: "Mã đặt lịch",
    contractId: "Mã hợp đồng",
    transferContent: "Nội dung chuyển khoản",
    bank: "Ngân hàng",
    accountName: "Chủ tài khoản",
    accountNumber: "Số tài khoản",
    method: "Phương thức thanh toán",
    status: "Trạng thái",
    download: "Tải hóa đơn (PDF)",
    back: "Quay lại trang KOL",
    schedule: "Xem lịch của tôi",
    amount: "Tổng thanh toán",
    countdown: "Thời gian còn lại: {time}",
    countdownExpired: "Hết thời gian thanh toán",
    countdownUnavailable: "Không khả dụng để thanh toán",
    qrAlt: "Mã QR thanh toán",
    summaryHeading: "Tổng quan đặt lịch",
  },
  terms: {
    heading: "Điều khoản sử dụng",
    body:
      "Khi đặt lịch, bạn cam kết cung cấp thông tin chính xác, thanh toán đúng hạn và hợp tác theo thỏa thuận.\n" +
      "Booking KOL sẽ liên hệ nếu có thay đổi lịch trình hoặc yêu cầu bổ sung.",
    agree: "Tôi đồng ý",
  },
};
